config/routes.rb
Rails.application.routes.draw do
	mount Bootsy::Engine => '/bootsy', as: 'bootsy'
	
  devise_for :system_users, path: 'account', :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'home#index'
  get 'about', to: 'home#about'

  resources :system_users, only: [:show, :edit, :update]
  resources :travels
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/system_user.rb
class SystemUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :avatar, AvatarUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :travels
  validates :email, uniqueness: true
  validates :username, uniqueness: true
end

app/models/travel.rb
class Travel < ApplicationRecord
	# include Bootsy::Container
	mount_uploader :cover, AvatarUploader
	belongs_to :system_user
	belongs_to :bootsy_image_gallery, optional: true
	validates_presence_of :title, :description, :content, :cover, :system_user_id, :message => "can't be blank"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def index
		@travels = Travel.limit(4)
		@system_users = SystemUser.limit(4)
	end

	def about
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	before_action :authenticate_system_user!, only: [:edit, :update]
	layout proc{ |controller| system_user_signed_in? ? "system_user" : "application" }

	def edit
    @system_user = current_system_user
  end

	# protected
	# def after_update_path_for(resource)
 #    system_user_path(resource)
 #  end

  private
  def sign_up_params
    params.require(:system_user).permit(:username, :email, :password, :password_confirmation)
  end

  def after_update_path_for(_)
    edit_system_user_registration_path
  end
end

app/controllers/system_users_controller.rb
class SystemUsersController < ApplicationController
	before_action :authenticate_system_user!
	layout "system_user", only: :show

	def show
		@system_user = SystemUser.find(params[:id])
		@travels = @system_user.travels.paginate(:page => params[:page], per_page: 10)
	end

	def edit
		@system_user = SystemUser.find(params[:id])
	end

	def update
		@system_user = SystemUser.find(params[:id])
	  if @system_user.update(system_user_params)
	    redirect_to root_path
	  else
	    render 'edit'
	  end
	end

	private
	def system_user_params
    params.require(:system_user).permit(:username, :signature, :avatar)
  end
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
	before_action :authenticate_system_user!, only: [:new, :edit, :create, :update]

	def index
		@travels = Travel.includes(:system_user).paginate(:page => params[:page], per_page: 6)
	end

	def new
		@travel = Travel.new
	end

	def show
		@travel = Travel.find(params[:id])
	end

	def edit
		@travel = Travel.find(params[:id])
	end

	def create
		@travel = Travel.new(travel_params)
		if @travel.save
			redirect_to @travel
		else
			render 'new'
		end
	end

	def update
	  @travel = Travel.find(params[:id])
	  if @travel.update(travel_params)
	    redirect_to @travel
	  else
	    render 'edit'
	  end
	end

	def destroy
	  @travel = Travel.find(params[:id])
	  @travel.destroy
	  redirect_to travels_path
	end

	private
	def travel_params
    params.require(:travel).permit(:title, :description, :content, :cover, :system_user_id, :bootsy_image_gallery_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/about.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url(<%= asset_path('banner/about-bg.jpg') %>)">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="page-heading">
          <h1>About Me</h1>
          <hr class="small">
          <span class="subheading">This is what I do.</span>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <em>
      <p>From tomorrow on, I will be a happy man
        <br/>Grooming, chopping, and traveling all over the world
        <br/>From tomorrow on, I will care foodstuff and vegetable
        <br/>Living in a house towards the sea, with spring blossoms
      </p>
      <p>From tomorrow on, write to each of my dear ones
        <br/>Telling them of my happiness
        <br/>What the lightening of happiness has told me, I will spread it to each of them
      </p>
      <p>Give a warm name for every river and every mountain
        <br/>Strangers, I will also wish you happy
        <br/>May you have a brilliant future
        <br/>May your lovers eventually become spouse
        <br/>May you enjoy happiness in this earthly world
        <br/>I only wish to face the sea, with spring flowers blossoming
      </p>
      </em>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<!-- Carousel
================================================== -->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1" class=""></li>
    <li data-target="#myCarousel" data-slide-to="2" class=""></li>
  </ol>
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag 'banner/1.jpg' %>
      <div class="container">
        <div class="carousel-caption">
          <span>
          <h1>On the Road.</h1>
          <p>Life is not just drifting along, life also has the poem and the distant view...</p>
          </span>
        </div>
      </div>
    </div>
    <div class="item">
      <%= image_tag 'banner/2.jpg' %>
      <div class="container">
        <div class="carousel-caption">
          <span class="pull-right text-left">
          <h1>Voices of the Mountains.</h1>
          <p>To me a mountain seems to stand for silence;</p>
          <p>ranges rear up like great waves in the distance yet remain quiet as cold clouds;</p>
          <p>ordinary barren summits open hungry lips heavenward...</p>
          </span>
        </div>
      </div>
    </div>
    <div class="item">
      <%= image_tag 'banner/3.jpg' %>
      <div class="container">
        <div class="carousel-caption text-right">
          <span class="text-left">
          <h1>Footprints in the Sand.</h1>
          <p>He dreamt he was walking with the Lord. Across the sky flashed scenes of his life.</p>
          <p>For each scene, he noticed two sets of footprints in the sand; one belonged to him, and the other to the Lord..</p>
          </span>
        </div>
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div><!-- /.carousel -->

<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">
  <!-- Three columns of text below the carousel -->
  <div class="row">
    <% @system_users.each do |system_user| %>
      <div class="col-lg-3">
        <div class="text-center">
        <%= image_tag "#{system_user.avatar_url if system_user.avatar?}", class: "img-circle", style: "width:140px; height: 140px;" %>
        <h2><%= system_user.username %></h2>
        </div>
        <p><%= system_user.signature %></p>
        <p class="text-center"><%= link_to("View details »", edit_system_user_path(system_user), :class => "btn btn-default") %></p>
      </div><!-- /.col-lg-4 -->
    <% end %>
  </div><!-- /.row -->

  <!-- START THE FEATURETTES -->

  <% @travels.each_with_index do |travel, index| %>
    <hr class="featurette-divider">
    <div class="row featurette">
      <div class="col-md-6 <%="col-md-push-6" if index % 2 == 0%>">
        <h2 class="featurette-heading">
          <%= link_to(travel_path(travel.id)) do %>
            <%= travel.title %><span class="text-muted">/<%= travel.created_at %></span>
          <% end %>
        </h2>
        <p class="text-muted"><%= travel.description %></p>
      </div>
      <div class="col-md-6 <%="col-md-pull-6" if index % 2 == 0%>">
        <%= image_tag "#{travel.cover_url if travel.cover?}", class: "featurette-image img-fluid mx-auto", style: "width:550px; height: 220px;" %>
      </div>
    </div>
  <% end %>
  <hr class="featurette-divider">
  <p class="text-right" style="margin: 0px;"><%= link_to("More »", travels_path) %></p>
</div><!-- /.container -->

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

<style>
  #myCarousel img{
    min-width: 100%;
    height: 100%;
  }
  .featurette-divider{
    margin-top: 50px;
  }
  .marketing{
    margin-top: 50px;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render partial: "shared/header" %>
    <%= yield %>
  	<%= render partial: "shared/footer" %>
  </body>
</html>

app/views/layouts/system_user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render partial: "shared/header" %>
    <div class="row" style="margin: 20px;">
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="col-md-12">
            <div class="col-md-4">
              <%= image_tag "#{@system_user.avatar_url if @system_user.avatar?}", class: "img-circle", style: "width:140px; height: 140px;" %>
            </div>
            <div class="col-md-8">
              <h2><%= link_to @system_user.username, edit_system_user_path(@system_user) %></h2>
              <span class="text-muted"><%= @system_user.email %></span>
              <p>last_sign_in: <%= @system_user.current_sign_in_at %></p>
            </div>
            </div>
            <div class="col-md-12">
              <%= @system_user.signature %>
              <p class="text-right">
                <%= link_to("Change Pwd", edit_system_user_registration_path, :class => "btn btn-default") %>
                <%= link_to("Create Travel", new_travel_path, :class => "btn btn-default") %>
              </p>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-8">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_footer.html.erb
<hr class="featurette-divider">
<!-- /END THE FEATURETTES -->

<!-- FOOTER -->
<footer class="text-center">
  <p><a href="#">Back to top</a></p>
  <p>© 2014 Company, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default" style="margin: 0px;">
  <div class="container-fluid">
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <a href="#" class="navbar-brand">Carousel</a>
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to("Home", root_path) %></li>
        <li><%= link_to("Travels", travels_path) %></li>
        <li><%= link_to("About", about_path) %></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <% if system_user_signed_in? %>
        <li><%= link_to(current_system_user.username, system_user_path(current_system_user)) %></li>
        <li><%= link_to("Sign out", destroy_system_user_session_path, :method => :delete) %></li>
        <% else %>
        <li><%= link_to("Login", new_system_user_session_path) %></li>
        <li><%= link_to("Sign up", new_system_user_registration_path) %></li>
        <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/system_users/edit.html.erb
<%= form_for(@system_user) do |f|%>
	<div class="row">
	  <div class="col-md-6 col-md-offset-3" style="margin-top: 20px;">
			<div class="panel panel-default">
	      <div class="panel-body">
		      <% if @system_user.errors.any? %>
				    <div id="error_explanation">
				      <h2>
				        <%= pluralize(@system_user.errors.count, "error") %> prohibited
				        this system_user from being saved:
				      </h2>
				      <ul>
				        <% @system_user.errors.full_messages.each do |msg| %>
				          <li><%= msg %></li>
				        <% end %>
				      </ul>
				    </div>
				  <% end %>
				  <div class="form-group">
			      <%= @system_user.email %>
			    </div>
					<div class="form-group">
			      <%= f.label :username, "username:" %>
			      <%= f.text_field :username, class: 'form-control', required: true %>
			    </div>
			    <div class="form-group">
			      <%= f.label :avatar, "avatar:" %>
			      <%= f.file_field :avatar %>
			    </div>
			    <div class="form-group">
			      <%= f.label :signature, "signature:" %>
			      <%= f.text_area :signature, class: 'form-control', size: "100", required: true %>
			    </div>
			    <div class="form-group text-right">
		    		<%= f.submit "Save", class: "btn btn-primary" %>
		    	</div>
	    	</div>
    	</div>
		</div>
	</div>
<% end %>

app/views/system_users/show.html.erb
<div class="panel-group" id="accordion" aria-multiselectable="true">
  <% @travels.each do |travel|%>
  <div class="panel panel-default">
    <div class="panel-heading" id="<%="heading#{travel.id}"%>">
      <h5 class="mb-0">
        <a data-toggle="collapse" data-parent="#accordion" href="<%="#collapse#{travel.id}"%>" aria-expanded="true" aria-controls="<%="collapse#{travel.id}"%>">
          <%= travel.title %>
        </a>
        <small class="pull-right"><%= travel.system_user.username %>/<%= travel.created_at %></small>
      </h5>
    </div>

    <div id="<%="collapse#{travel.id}"%>" class="collapse" role="tabpanel" aria-labelledby="<%="heading#{travel.id}"%>">
      <div class="panel-body">
        <p class="text-info"><em><%= travel.description %></em><p>
        <p class="text-right">
          <%= link_to("Detail", travel_path(travel), :class => "btn btn-default") %>
          <%= link_to("Edit", edit_travel_path(travel), :class => "btn btn-default") %>
          <%= link_to 'Destroy', travel_path(travel),
              class: "btn btn-default",
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
        </p>
      </div>
    </div>
  </div>
  <% end %>
  <hr/>
  <div class="text-right" style="margin-right: 50px;">
    <%= will_paginate @travels, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/travels/_form.html.erb
<%= form_for(@travel) do |f|%>
	<div class="row">
	  <div class="col-md-8 col-md-offset-2" style="margin-top: 20px;">
			<div class="panel panel-default">
	      <div class="panel-body">
		      <% if @travel.errors.any? %>
				    <div id="error_explanation">
				      <h2>
				        <%= pluralize(@travel.errors.count, "error") %> prohibited
				        this travel from being saved:
				      </h2>
				      <ul>
				        <% @travel.errors.full_messages.each do |msg| %>
				          <li><%= msg %></li>
				        <% end %>
				      </ul>
				    </div>
				  <% end %>
					<div class="form-group">
						<%= f.hidden_field :system_user_id, value: current_system_user.id %>
			      <%= f.label :title, "title:" %>
			      <%= f.text_field :title, class: 'form-control', required: true %>
			    </div>
			    <div class="form-group">
			      <%= f.label :cover, "cover:" %>
			      <%= f.file_field :cover %>
			    </div>
			    <div class="form-group">
			      <%= f.label :description, "description:" %>
			      <%= f.text_area :description, class: 'form-control', size: "100", required: true %>
			    </div>
			    <div class="form-group">
			      <%= f.label :content, "content:" %>
			      <%= f.bootsy_area :content, class: 'form-control', rows: "20" %>
			    </div>
			    <div class="form-group text-right">
		    		<%= f.submit "Publish", class: "btn btn-primary" %>
		    	</div>
	    	</div>
    	</div>
		</div>
	</div>
<% end %>

app/views/travels/edit.html.erb
<%= render 'travels/form' %>

app/views/travels/index.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url(<%= asset_path('banner/running.jpg') %>)">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <div class="page-heading">
          <h1 class="text-right"><em>Let's go...</em></h1>
        </div>
      </div>
    </div>
  </div>
</header>
<div class="container">
  <div class="panel panel-default">
    <div class="panel-body">
    <% @travels.each_with_index do |travel, index| %>
      <div class="col-md-4">
        <div class="text-center">
        <%= image_tag "#{travel.cover_url if travel.cover?}", style: "width:350px; height: 190px;" %>
        <h2><%= travel.title %></h2>
        </div>
        <p class="text-muted"><em><%= travel.description %></em></p>
        <p><%= link_to("View details »", travel_path(travel), :class => "btn btn-default") %></p>
      </div><!-- /.col-md-4 -->
      <% if (index+1)%3 == 0 %><div class="col-md-12"><hr/></div><% end %>
    <% end %>
    </div>
    <div class="text-center">
      <%= will_paginate @travels, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>

app/views/travels/new.html.erb
<%= render 'travels/form' %>

app/views/travels/show.html.erb
<header class="intro-header" style="background-image: url(<%=@travel.cover? ? @travel.cover_url : "images/sheep_lake1.jpg" %>)">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="post-heading">
          <h1><%= @travel.title %></h1>
          <h2 class="subheading"><em><%= @travel.description %></em></h2>
          <span class="meta">Posted by <a href="#"><u><%= @travel.system_user.username %></u></a> on <%= @travel.created_at %></span>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Post Content -->
<article>
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <%= @travel.content.html_safe %>
      </div>
    </div>
  </div>
</article>